### ISSUE TITLE
attribute missing in GameConfig

### ISSUE THREAD

**Issue by jakobzmrzlikar** [mucamaca/gravity_connect#10]
when I run I get

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1553, in __call__
    return self.func(*args)
  File "GUI.py", line 68, in mouse_click
    self.place_token(mouse_x, mouse_y)
  File "GUI.py", line 117, in place_token
    if self.grid.check_win():
  File "/media/work/Projects/gravity-connect/src/grid.py", line 77, in check_win
    if i + config.win_len < self.x_size:
AttributeError: 'GameConfig' object has no attribute 'win_len'

**Comment by mucamaca** [comment]
It's already fixed
